Repository ember-template-lint/ember-template-recast, pull requests merged in 2019-10, with the labels that each got.

#123 Reexport `builders` from `@glimmer/syntax`
  src/index.js
Labels: enhancement

#132 Ensure chained inverses are properly printed.
  src/parse-result.js
  tests/smoke-test.js
Labels: bug

#134 package.json: Add more metadata
  package.json
Labels: internal

#135 Ensure `TextNode`s are quoted in `AttrNode.value`
  src/parse-result.js
  tests/parse-result-test.js
Labels: bug

#136 Fix issues with adding to a `ConcatStatement`
  package.json
  tests/parse-result-test.js
  yarn.lock
Labels: bug

#140 Handle attr change from text node to mustache
  src/parse-result.js
  tests/parse-result-test.js
Labels: bug

#145 Use execa instead of child_process.spawn
  .github/workflows/ci.yml
  package.json
  tests/ember-template-recast-test.js
  yarn.lock
Labels: internal

#143 Add Windows and macOS CI testing.
  .github/workflows/ci.yml
  tests/ember-template-recast-test.js
Labels: internal

#154 fix: Make it possible to annotate nodes
  src/parse-result.js
  tests/parse-result-test.js
Labels: enhancement
