Repository ember-template-lint/ember-template-recast, pull requests merged in 2021-11, with the labels that each got.

#670 Update eslint related packages to latest
  package.json
  yarn.lock
Labels: internal

#653 Allow updating `quoteType` and `isValueless` of AttrNodes, and `quoteType` of StringLiterals
  README.md
  src/custom-nodes.ts
  src/index.ts
  src/parse-result.test.ts
  src/parse-result.ts
Labels: enhancement

#679 Fix modifying valueless attrs
  src/parse-result.test.ts
  src/parse-result.ts
Labels: bug

#689 Update Typescript configuration
  tsconfig.json
Labels: internal

#95 Fix the scenario where block params are on a new line
  src/parse-result.test.ts
  src/parse-result.ts
  src/smoke.test.ts
  src/utils.test.ts
  src/utils.ts
  tsconfig.json
Labels: bug

#661 Add a `yarn perf:benchmark` script
  .eslintrc.js
  .github/workflows/benchmark.yml
  package.json
  scripts/benchmark.mjs
  yarn.lock
Labels: internal
