Repository ember-template-lint/ember-template-recast, pull requests merged in 2025-04, with the labels that each got.

#998 Widen glimmer syntax range
  package.json
Labels: bug

#1000 Drop support for node < 18.12
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  .gitignore
  package.json
Labels: breaking

#1001 Migrate to pnpm
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  package.json
  pnpm-lock.yaml
  yarn.lock
Labels: internal

#1002 Setup release-plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal
